### ISSUE TITLE
Fails to build/run with gtk4 4.18.2

### ISSUE THREAD

**Issue by justjakka** [wwmm/easyeffects#3728]
### EasyEffects Version

v7.2.3 / latest commit

### What package are you using?

Other (specify below)

### Distribution

Arch Linux

### Describe the bug

Easyeffects fails to run or build on a system with gtk4 4.18.2

### Expected Behavior

Easyeffects compiles and runs without issues

### Debug Log

When linking the following error appears:

```
/usr/bin/ld: /usr/lib/libgtk-4.so: undefined reference to `png_set_cICP@PNG16_0'
/usr/bin/ld: /usr/lib/libgtk-4.so: undefined reference to `png_get_cICP@PNG16_0'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by wwmm** [comment]
That is strange. I also use Arch Linux and I had no issues rebuilding the AUR package. After the gtk4 update. How did you rebuild your package ?

**Comment by wwmm** [comment]
Hum... I do not know what could be happening on your computer. Our automated Arch Linux build is still working here on github https://github.com/wwmm/easyeffects/actions/runs/14062333076/job/39376057336. I wonder if the gtk4 update somehow got corrupted on your end. Did you try to reinstall it?

**Comment by justjakka** [comment]
yes, i have tried reinstalling it and it did nothing.
running the precompiled binary yeilds the same symbol lookup error

**Comment by wwmm** [comment]
> yes, i have tried reinstalling it and it did nothing. running the precompiled binary yeilds the same symbol lookup error

It may seem a stupid question but did you reboot the computer after the update? From time to time there are updates that require are reboot for no obvious reason. In the past some people had really weird problems after Pipewire(or Pulseaudio) updates and in the end the fix was a reboot. They did not think it would be necessary but it was.

**Comment by justjakka** [comment]
naturally i also have tried that. unfortunately that didnt fix my issue

**Comment by wwmm** [comment]
> after completely reinstalling the system the issue persists, even though `png_get_cICP@PNG16_0` is in libgtk library

Hum... This is so strange. Our automated build is still fine as well as my computer. The error suggests that something went wrong in the `libpng` library installation. But I would expect almost anything related to gtk4 to also be broken.

Try to install `gtk4-demos` to see if the demo is working. As far as I remember EasyEffects does not even try to to stuff related to png. So other gtk4 apps should be affected by this too.

**Comment by justjakka** [comment]
ok, now when you mentioned libpng i was using 1.6.44 (needed a specific patch on my machine). updated to 1.6.47 and it works.
